dataset <- read.table("household_power_consumption.txt",sep=";",header=TRUE,stringsAsFactors=FALSE,na.strings="?")
dataset$Date <-as.Date(dataset$Date,format="%d/%m/%Y") 
Consumption<-subset(dataset,Date%in%as.Date(c("2007-02-01","2007-02-02")))
Consumption$Datetime <-as.POSIXct(paste(Consumption$Date,Consumption$Time))
Consumption$Global_active_power <- as.numeric(Consumption$Global_active_power)
DateTime<-(Consumption$Datetime <- strptime(Consumption$Datetime, format = "%Y-%m-%d %H:%M:%S"))
png(file="plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(DateTime,Consumption$Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowatts)")
plot(DateTime,Consumption$Voltage,type="l",xlab="",ylab="Voltage")
plot(DateTime,Consumption$Sub_metering_1,type="l",xlab="",ylab="Energy_sub_metering")
lines(DateTime,y=Consumption$Sub_metering_2,col="red")
lines(DateTime,y=Consumption$Sub_metering_3,col="blue")
plot(DateTime,Consumption$Global_reactive_power,type="l",xlab="",ylab="Global_reactive_power")
while (!is.null(dev.list()))  dev.off()